name:  Generate_SBOM_cycloneDX

on: 
  push:
  workflow_dispatch:
  
jobs:
  scribe-report-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:

    - name: Generate cyclonedx json SBOM
      id: valint_json
      uses: scribe-security/action-bom@master
      with:
       # type: git
        target: docker:mongo-express
        output-file: 'mongo-express.json'
        format: json
        scribe-enable: true
        scribe-client-id: ${{ secrets.clientid }}
        scribe-client-secret: ${{ secrets.clientsecret }}
        product-key: juiceShop
        
    - uses: actions/upload-artifact@v2
      with:
        name: scribe-sbom
        path: ${{ steps.valint_json.outputs.OUTPUT_PATH }}




