name: sbom

on: 
  push

jobs:
  scribe-report-test:
    runs-on: ubuntu-latest
    steps:
     uses: scribe-security/action-bom@master
     with:
        target: git:https://github.com/neha-bw/juice-shop.git
        format: [attest, statement, attest-slsa, statement-slsa]
        scribe-enable: true
        scribe-client-id: ${{ secrets.clientid }}
        scribe-client-secret: ${{ secrets.clientsecret }}

     uses: scribe-security/action-verify@master
     with:
        target: git:https://github.com/neha-bw/juice-shop.git
        format: [attest, statement, attest-slsa, statement-slsa]
        scribe-enable: true
        scribe-client-id: ${{ secrets.clientid }}
        scribe-client-secret: ${{ secrets.clientsecret }}
