name:  Generate_SBOM_workflow

on: 
  push:
  workflow_dispatch:
  
jobs:
  scribe-report-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Generate cyclonedx json SBOM
      id: valiant_bom
      uses: scribe-security/action-bom@master
      with:
        type: git
        target: 'https://github.com/neha-bw/juice-shop.git'
        format: json
        scribe-enable: true
        scribe-client-id: ${{ secrets.clientid }}
        scribe-client-secret: ${{ secrets.clientsecret }}
        product-key: juiceShop
        
    - uses: actions/upload-artifact@v2
      with:
        name: sbom-test
        path: scribe/valint

    - name: valint attest
      uses: scribe-security/action-bom@master
      with:
        target: 'https://github.com/neha-bw/juice-shop.git'
        format: attest
        
    - uses: actions/upload-artifact@v2
      with:
        name: sbom-attest
        path: scribe/valint
