name:  scribe_github_workflow

on: 
  push
  
jobs:
  scribe-report-test:
    runs-on: ubuntu-latest
    steps:
    - name: Generate cyclonedx json SBOM
      uses: scribe-security/action-bom@master
      with:
        type: git
        target: 'https://github.com/neha-bw/juice-shop.git'
        format: json
