name:  Generate_SBOM_workflow

on: 
  push:
  workflow_dispatch:
  
jobs:
  scribe-report-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Generate cyclonedx json SBOM
      id: valiant_bom
      uses: scribe-security/action-bom@master
      with:
        type: git
        target: 'https://github.com/neha-bw/juice-shop.git'
        format: json
        scribe-enable: true
        scribe-client-id: ${{ secrets.clientid }}
        scribe-client-secret: ${{ secrets.clientsecret }}
        product-key: juiceShop
        
    - uses: actions/upload-artifact@v2
      with:
        name: sbom-test
        path: scribe/valint

    - name: Generate SLSA provenance statement
      id: valint_slsa_statement
      uses: scribe-security/action-bom@master
      with:
        target: git:https://github.com/neha-bw/juice-shop.git
        format: statement-slsa
        scribe-enable: true
        scribe-client-id: ${{ secrets.clientid }}
        scribe-client-secret: ${{ secrets.clientsecret }}
        product-key: juiceShop
          
    - uses: actions/upload-artifact@v2
      with:
        name: provenance
        path: ${{ steps.valint_slsa_statement.outputs.OUTPUT_PATH }}
        
    - name: valint verify
      uses: scribe-security/action-verify@master
      with:
        target: git:https://github.com/neha-bw/juice-shop.git
        input-format: attest-slsa
      
    - uses: actions/upload-artifact@v2
      with:
        name: attest
        id: valint_slsa_attest
        path: ${{ steps.valint_slsa_attest.outputs.OUTPUT_PATH }}
