name: "ZAP Baseline Scan"

on: workflow_dispatch

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Juice Shop preview instance
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
         #  token: ${{ secrets.GITHUB_TOKEN }}
           docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
           target: 'https://demo.testfire.net/'
           rules_file_name: '.zap/rules.tsv'
           cmd_options: '-a'
